export const SELECTION_CREATE = 'SELECTION_CREATE';
export const SELECTIONS_LIST_ERROR = 'SELECTIONS_LIST_ERROR';
export const SELECTIONS_LIST_FETCH = 'SELECTIONS_LIST_FETCH';
export const SELECTIONS_LIST_SUCCESS = 'SELECTIONS_LIST_SUCCESS';
